name: six
version: 0.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.3
  pedantic: ^1.11.1
  get: ^4.3.0
  flutter_svg: ^0.22.0
  path: ^1.8.0
  extended_masked_text: ^2.2.1
  file_picker: ^4.0.0
  flutter_mailer: ^2.0.0
  sqflite: ^2.0.0+3
  flutter_screenutil: 5.0.0+2
  get_storage: ^2.0.3
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.6
  encrypt: ^5.0.0
  logger: 1.1.0
  dio: 4.0.0
  webview_flutter: ^2.0.10
  pretty_dio_logger: ^1.1.1
  firebase_remote_config: ^0.10.0+5
  image_picker: ^0.8.1+3
  cached_network_image: ^3.0.0
  path_provider: 2.0.2
  syncfusion_flutter_charts: ^19.2.59
  dotted_border: ^2.0.0
  month_picker_dialog: ^0.4.0
  catcher: ^0.6.7
  url_launcher: ^6.0.8
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  permission_handler: ^8.1.2
  flutter:
    sdk: flutter
  r_dart_library: 0.4.0-nullsafety.0

dev_dependencies:
  flutter_native_splash: ^1.2.1
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_svg: ^0.22.0

flutter:
  assets:
  - assets/images/Calendar.png
  - assets/images/Call.png
  - assets/images/Discount.png
  - assets/images/Home.png
  - assets/images/Home_active.png
  - assets/images/Location.png
  - assets/images/Message.png
  - assets/images/Profile.png
  - assets/images/Profile_active.png
  - assets/images/Search.png
  - assets/images/bell.png
  - assets/images/buy.png
  - assets/images/camera_only.png
  - assets/images/charity_ticket.png
  - assets/images/charity_ticket_select.png
  - assets/images/discoun_active.png
  - assets/images/edit_icon.png
  - assets/images/email.png
  - assets/images/error_dialog.png
  - assets/images/feedback.png
  - assets/images/food.png
  - assets/images/history.png
  - assets/images/home_new.png
  - assets/images/image_picker.png
  - assets/images/man.png
  - assets/images/onb_1.png
  - assets/images/onb_2.png
  - assets/images/onb_3.png
  - assets/images/onboarding_5.png
  - assets/images/onboarding_6.png
  - assets/images/onboarding_7.png
  - assets/images/ons_1.png
  - assets/images/ons_2.png
  - assets/images/ons_3.png
  - assets/images/phone.png
  - assets/images/privacy.png
  - assets/images/profile_new.png
  - assets/images/pucrchase_social_active.png
  - assets/images/purchase.png
  - assets/images/purchase_icon.png
  - assets/images/purchase_social.png
  - assets/images/qr_border.png
  - assets/images/request.png
  - assets/images/select_voucher.png
  - assets/images/six_logo-removebg-preview.jpg
  - assets/images/six_logo.png
  - assets/images/success_redem.png
  - assets/images/super_market.png
  - assets/images/support.png
  - assets/images/term_c.png
  - assets/images/ticket.png
  - assets/images/ticket_click.png
  - assets/images/transport.png
  - assets/images/vendor_onb1.png
  - assets/images/vendor_onb2.png
  - assets/images/voucher_card_1.png
  - assets/images/voucher_filter.png
  - assets/images/
  - assets/locales/
  uses-material-design: true

flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images/
  fonts:
  - fonts/
