name: six
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  get: 4.1.4
  flutter_screenutil: 5.0.0+2
  get_storage: 2.0.2
  firebase_core: 1.2.1
  firebase_messaging: 10.0.1
  flutter_local_notifications: 6.0.0
  encrypt: ^5.0.0
  logger: 1.0.0
  retrofit: 2.0.0
  dio: 4.0.0
  catcher: 0.6.6
  firebase_remote_config: 0.10.0+1
  firebase_auth_oauth: 1.0.1
  firebase_auth: ^1.3.0
  google_sign_in: 5.0.4
  path_provider: 2.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  retrofit_generator: ^2.0.0+1
  build_runner: 2.0.4
  json_serializable: ^4.1.3
  change_app_package_name: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/locales/
  uses-material-design: true

